sudo: false
language: php

php:
  - 5.6

install:
  - composer require satooshi/php-coveralls

before_script:
  - mv src/Config/App.example.php src/Config/App.php

script:
  - src/vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry src/vendor/bin/coveralls -v
