sudo: false
language: php

php:
  - 7.0
  - 5.6
  - 5.3
  - 5.4
  - 5.5

install:
  - composer install
  - composer require satooshi/php-coveralls

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - travis_retry vendor/bin/coveralls